version: '3'
services:
  mysql:
    image: 'bitnami/mysql:5.7'
    ports:
      - '5706:3306'
    environment:
      - MYSQL_DATABASE=test1
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Shanghai
    volumes:
      - ./Shanghai:/etc/localtime
      - ./my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
#      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/bitnami/mysql/data
#      - ./run.sh:/run.sh
      - ./innblock:/usr/local/bin/innblock
      - ./bcview:/usr/local/bin/bcview
